### ISSUE TITLE
Keyboard navigation should jump to sidebar before the main content

### ISSUE THREAD

**Issue by adborden** [caciviclab/odca-jekyll#228]
To reproduce:
1. open https://www.opendisclosure.io/office/oakland/2018-11-06/mayor/
1. Hit tab a few times through the top nav, keep going

### Expected

Focus should jump to the sidebar before jumping to main page.

### Actual

Focus jumps to the candidate list first.

Also, add a skip nav.

**Comment by adborden** [comment]
Assinging this to @r-i-c-h

**Comment by r-i-c-h** [comment]
The issue that is causing this behavior is that in ballot-layout.html the <nav> `<div class="l-ballot__nav">` is being injected *after* the page contents of `<div class="l-ballot__main">`.

The right answer = Rearrange order of the <div>s, because <nav> should be above content. But there is a lot of funky CSS that would require changes across all breakpoints. I'm happy to do it, but I know someone else was working on the CSS on Tues, and I don't want to interfere with what they're doing. (+I'd kill the old-skool `clear:both`/float layouts to use flexbox instead)

The bad answer = There is an html tag property `tabindex=""` which is specifically for this exact sort of thing, but every source I've found warns *against* using it as it would require attaching the tabindex to tons of elements + it's on the deprecation chopping block. (Though none of those sources provide alternative suggestions 😠)

The super hacky JS workaround = Setup keypress event listeners to check the current focused element, and then force the element.focus() to jump around. Would require adding some #id to get from the right 'first' to the right 'last'. Would also need to listen for shift+tab in order to move backwards in the proper order. Messy but theoretically doable. 

Thoughts?

**Comment by adborden** [comment]
Awesome, thanks for looking into this!

Let's try the `tabindex` solution first. I think you would only need to
add it to the ballot nav, which shouldn't be a big deal.

--
Aaron D Borden
Human and Hacker
