### ISSUE TITLE
Measure V page isn't displaying IEs

### ISSUE THREAD

**Issue by sfdoran** [caciviclab/odca-jekyll#277]
Back end has IE supporting measure V but it isn't showing on the Measure V page - maybe because the measure doesn't have any contribution data? Same IE is showing on the pages for other impacted measures.

![image](https://user-images.githubusercontent.com/19939684/47238272-897c9b00-d396-11e8-868f-bfca4bc66698.png)

**Comment by ckingbailey** [comment]
Yeah, @sfdoran, you got it. It's not showing up on V because there's no total_contributions data for either supporting or opposing. The committee shows up on W because W has total contributions opposing. The way it works now there has to be total contributions for either supporting or opposing to display anything.

Rather than depending on total_contributions to display any finance data we should make two checks. For the top two sections, "Contributions by type" and "Contributions by region" we can keep the total_contributions check. Then down at the bottom, for "Spending breakdown by committee" we ought to tally the numbers on `amount` for each org (`supporting_organizations[#].amount`) and then check if that total is > 0

**Comment by ckingbailey** [comment]
* Or check if any org has an amount > 0

**Comment by adborden** [comment]
I *think* we fixed this on the candidate layout, but I guess not
referendums. I would check that to see if the same solution can be used
here.

--
Aaron D Borden
Human and Hacker
