### ISSUE TITLE
How is waffle working for folks?

### ISSUE THREAD

**Issue by adborden** [caciviclab/odca-jekyll#299]
Is waffle working? People using it seem to find it useful, but a lot of folks aren't using it. Do we need to document it more prominently? Do we need to give a quick demo/tutorial?

**Comment by r-i-c-h** [comment]
I mean, it's working (def better than Trello which I hate) but I'll admit I don't really check it much. Does it include both front and back repos? 

1.  I think I'm just used to looking at a Github Issues list so it's not usually the first thing I check.
2. Are the cards sorted by priority? 
3. Does it include cards for issues from *both* front and back repos? 
4. I think there are a lot of tickets that could be closed.

**Comment by r-i-c-h** [comment]
( srry. errant click. )

**Comment by ckingbailey** [comment]
It's not the first place I go only because I have to filter for front end issues on Waffle whereas on Github I can go straight to the repo for those issues. I didn't know before that Waffle was prioritized though, so I'll probably check it more in the New Year.
What all do we get from Waffle--just the prioritization and the automatic closing of issues tagged in PRs? Is there more we could be getting from it?

**Comment by adborden** [comment]
Waffle is closing, we'll be moving to ZenHub and then check in after using that for a bit.
