### ISSUE TITLE
Referendum page: Don't link to contributions table from the ballot measure committee

### ISSUE THREAD

**Issue by anlawyer** [caciviclab/odca-jekyll#350]
Let's move the link to the contributor's table to be under "Contributions by region", the same way we link to the table for candidates. Linking to the table from the referendum committee feels odd, since the committee is listed under the "Expenditures".

**Comment by gauravmk** [comment]
In looking into it, the tables are for a specific committee and there can be multiple committees for a particular ballot measure. There was some discussion of maybe linking to the primary committee for a measure instead of including independent expenditures but I don't think that's nearly as clear either. For instance, for https://www.opendisclosure.io/referendum/oakland/2018-11-06/hotel-employee-minimum-wage-and-workplace-protections/ i'm not sure we mark which is the primary

Also I'm not sure it'll be obvious if the total contribution rollup amounts don't match the click through to the contribution table

**Comment by anlawyer** [comment]
@joshling1919 and I were chatting about this last week. Given what @gauravmk said in his previous above, we think a simple solution to this could be to change the text of the link to say something like "See all contributions to this committee" instead of the link being the name of the committee. Something like this (with better design, ofc):
<img width="862" alt="Screen Shot 2020-03-24 at 7 40 52 PM" src="https://user-images.githubusercontent.com/28023047/77496197-aaf17a00-6e07-11ea-9fe8-6d6c67a9f6be.png">

Does that sound like a good interim (or complete) solution to this issue? I think this issue came from the confusion that the current links from the committees are listed under "Spending breakdown by committee" but link to a _contributions_ table. This clarifying text could solve that problem. Any input, @ckingbailey, @sfdoran?
