### ISSUE TITLE
Search box should appear on all pages.

### ISSUE THREAD

**Issue by mikeubell** [caciviclab/odca-jekyll#395]
Currently search is only accessible on the /search page.  We should have a search box in the header.

**Comment by MrVantastic** [comment]
created a branch search-box for this ticket

**Comment by anlawyer** [comment]
I commented in slack about this task, so I'm re-posting it here for better visibility:

What does the design of this search field in the header / on each page look like?
- Should we have a search field in the header, and display search results on any page, rather than having the search page exist on its own? Does Algolia have some sort of drop down component that we can populate with results, instead of a separate search page? I think the current design/mock ups have this pattern of a search field in the header with a results drop down.
- Should we have a link/button in the header to redirect the user to the separate search page, and show the results on that page only? The search results would then link you to the other pages in the site, and by passing in the search query params in the url, we can navigate back to the last search with browser navigation.

Is there another design pattern anyone has been looking at for this?

**Comment by anlawyer** [comment]
We decided that to start with, the easiest path forward is to put a simple button / link on every page (maybe in the header?). Then we can explore the possibility of a search _box_ in the header as a future enhancement. @MrVantastic is going to be working on adding the link / button.
